### ISSUE TITLE
Create an initial example to install and use GlusterFS on Kubernetes

### ISSUE THREAD

**Issue by webwurst** [giantswarm/kubernetes-glusterfs#1]
Aim for [`StorageClass`](http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html)
Some findings/thoughts:
- [[slack/sig-storage]](https://kubernetes.slack.com/archives/sig-storage/p1477599300000583) the only supported write-by-many storage backend is glusterfs, cephfs, azurefile, or plane nfs
- nothing on [helm/charts](https://github.com/kubernetes/charts) yet
- [kubernetes/examples/volumes/glusterfs](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs) shows some simple steps when connecting to a glusterfs server outside of kubernetes
- Something about `StorageClass` for GlusterFS [Persistent Volume Provisioning / GlusterFS](https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning#glusterfs)
- Another blog post for [GlusterFS on Kubernetes](http://larmog.github.io/2016/10/15/kubernetes-on-scaleway---part-3/) but: "The solution described here is not the only way you can use to set up GlusterFS for your cluster. You can also use a DaemonSet or a PetSet and run your glusterfs-servers as containers [..]"
- Something to try:
  - [Running GlusterFS inside Kubernetes](https://github.com/wattsteve/glusterfs-kubernetes)
  - [GlusterFS cluster with Kubernetes](https://medium.com/@jaime_ecom/glusterfs-cluster-with-kubernetes-c09725d69900)
  - [GlusterFS PetSet](https://github.com/munnerz/k8s-gluster-petset)
- Also: [Hekete Kubernetes Integration](https://github.com/heketi/heketi/wiki/Kubernetes-Integration)

**Comment by webwurst** [comment]
Status: Best approach seemed to be this [wattsteve/glusterfs-kubernetes](https://github.com/wattsteve/glusterfs-kubernetes/tree/master/heketi-examples). Looks like this was moved to [heketi/heketi/extras/kubernetes](https://github.com/heketi/heketi/tree/master/extras/kubernetes) and will end up on https://github.com/gluster/gluster-kubernetes. [Steve Watt](https://github.com/wattsteve) will announce this as the central repository for the Kubernetes integration of Glusterfs at KubeCon on Wednesday.

I could follow [heketi/heketi/wiki/Kubernetes-Integration](https://github.com/heketi/heketi/wiki/Kubernetes-Integration) with some workarounds until the last point at:

```
heketi-client/bin/heketi-cli setup-openshift-heketi-storage
```

There I am getting an error like "Peer not part of the cluster" or similar. Maybe there is a problem with the `ServiceAccount` and namespace? Not sure yet, `heketi-cli` does not provide debug output. I could try talking to the API directly and check on the server logs. But this might also be a moving target for now, since there are changes in the repo, but not sure if the Docker image is always in sync.

**Comment by puja108** [comment]
As @teemow thinks that glusterFS is not a good enough system to deliver reliable results to users, especially if running inside a cluster, we decided to stop looking into this.

@webwurst ok if we close this?

**Comment by webwurst** [comment]
ok!
